web/router.ex
defmodule Hnet.Router do
  use Hnet.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Hnet.Account.Plugs.AssignUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Hnet do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/patient", PageController, :patient
    get "/admin", PageController, :administrator
    get "/doctor", PageController, :doctor
    get "/nurse", PageController, :nurse
    resources "/hospitals", HospitalController
  end

  scope "/", Hnet.Account do
    pipe_through :browser

    get "/login", AuthController, :signin
    post "/login", AuthController, :login
    post "/logout", AuthController, :logout
    resources "/users", UserController, only: [:index, :show, :delete]
    get "/profile", UserController, :edit_profile
    put "/profile", UserController, :update_profile
  end

  scope "/registration", Hnet.Account do
    pipe_through :browser

    get "/", RegistrationController, :index
    get "/patient", RegistrationController, :new_patient
    post "/patient", RegistrationController, :create_patient
    get "/admin", RegistrationController, :new_administrator
    post "/admin", RegistrationController, :create_administrator
    get "/doctor", RegistrationController, :new_doctor
    post "/doctor", RegistrationController, :create_doctor
    get "/nurse", RegistrationController, :new_nurse
    post "/nurse", RegistrationController, :create_nurse
  end

  # Other scopes may use custom stacks.
  # scope "/api", Hnet do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Hnet.LayoutView do
  use Hnet.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Hello Hnet!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link "HNet", to: page_path(@conn, :index), class: "navbar-brand" %>
        </div>
        
        <ul class="nav navbar-nav">
          <li><%= link "Hospitals", to: hospital_path(@conn, :index) %></li>
          <li><%= link "Users", to: user_path(@conn, :index) %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <%= if @current_user do %>
            <%= form_for @conn, auth_path(@conn, :logout), [as: :logout, id: "logout-form", hidden: true], fn _ -> %>
            <%= end %>
            <li><a href="#" onclick="document.getElementById('logout-form').submit(); return false;">Logout</a></li>
          <%= else %>
            <li><%= link "Sign Up", to: registration_path(@conn, :new_patient) %></li>
            <li><%= link "Sign In", to: auth_path(@conn, :login) %></li>
          <%= end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>